// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVDGQ3wvufgPZUgkXZDvJMOKnSf9KveU',
    appId: '1:625454460532:web:2bc3099f5ce57bcc626b21',
    messagingSenderId: '625454460532',
    projectId: 'telegram-bots-c3c1f',
    authDomain: 'telegram-bots-c3c1f.firebaseapp.com',
    storageBucket: 'telegram-bots-c3c1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpSZZWndSDcNrNV3EptEEvJefjBlj0yo',
    appId: '1:625454460532:android:1ff155ccbe24d102626b21',
    messagingSenderId: '625454460532',
    projectId: 'telegram-bots-c3c1f',
    storageBucket: 'telegram-bots-c3c1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGJayKxS8Yy4-lX-AMuS-uLXCOyMEcwM',
    appId: '1:625454460532:ios:baad6074dee34b48626b21',
    messagingSenderId: '625454460532',
    projectId: 'telegram-bots-c3c1f',
    storageBucket: 'telegram-bots-c3c1f.appspot.com',
    iosClientId: '625454460532-8g6evpua3i1ja99v71g5vn4rklhf9si2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksync',
  );
}
